### ISSUE TITLE
Issue with InitalizeComponent() method

### ISSUE THREAD

**Issue by ubedla** [MicrosoftDocs/mslearn-create-a-mobile-app-with-xamarin-forms#1]
I downloaded the same project and when I started to deploy it on my android emulator, an exception was thrown which is mentioned below.
System.TypeLoadException
  Message=Could not resolve type with token 0100000a from typeref (expected class 'ResourceLoadingQuery' in assembly '')

**Comment by patridge** [comment]
I'm not sure what that error might be, but it sounds like it's specific to your setup. Just to make sure, it might be worth trying to move the Android project to a shorter path, in case that was related to a path length issue. After that, try a clean and rebuild.
